<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!--
      Intentionally pinned. Needs to ship in Roslyn Features layer as well as in .NET SDK.
    -->
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <DebugType>none</DebugType>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <LangVersion>preview</LangVersion>

    <!-- NuGet -->
    <IsPackable>true</IsPackable>
    <IsShipping>true</IsShipping>
    <IsSourcePackage>true</IsSourcePackage>
    <!-- TODO2: once the package shape is established, bring it back over to SDK and try to reference locally from there. -->
    <PackageId>FileBasedProgramsSupport</PackageId>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <PackageDescription>
      Internal package containing shared helpers for file-based programs functionality. For use by editor extensions and CLI.
    </PackageDescription>
    <!-- Remove once https://github.com/NuGet/Home/issues/8583 is fixed -->
    <NoWarn>$(NoWarn);NU5128</NoWarn>
  </PropertyGroup>

  <!-- TODO2: use PackageReference to Roslyn packages to make things build. -->
  <ItemGroup>
    <ProjectReference Include="../../../Compilers/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.csproj" />
    <ProjectReference Include="../../../Dependencies/Contracts/Microsoft.CodeAnalysis.Contracts.Package.csproj" PrivateAssets="all" />
  </ItemGroup>

  <!-- Make sure the shared source files do not require any global usings -->
  <ItemGroup>
    <Using Remove="@(Using)" />
  </ItemGroup>
</Project>
